import { prisma } from "@/lib/prisma";
import type { SessionUser } from "@/lib/rbac";
import { getOverviewData } from "@/lib/queries/overview";

export interface SituationReport {
  date: string;
  content: string;
  isAutoGenerated: boolean;
  updatedAt: string;
  updatedByName: string | null;
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Plain-text draft assembled from on-file stats — a starting point the
 * viewer (ADMIN or WFC Intelligence/M2) always edits by hand before it
 * means anything as an actual SITREP; never presented as a finished
 * report on its own. */
export async function generateSitrepDraft(user: SessionUser, date: string): Promise<string> {
  const data = await getOverviewData(user);
  const lines: string[] = [];

  lines.push(`SITUATION REPORT — ${date}`);
  lines.push(
    `BPE 2026 Window: ${new Date(data.bpe.startDate).toLocaleDateString()} to ${new Date(data.bpe.endDate).toLocaleDateString()}`
  );
  lines.push("");
  lines.push("1. INCIDENTS");
  lines.push(`Logged (last 30 days): ${data.recentIncidentCount30d}`);
  lines.push(`Priority/flagged areas: ${data.priorityAreaCount}`);
  if (data.recentIncidents[0]) {
    const r = data.recentIncidents[0];
    lines.push(
      `Most recent: ${r.type} — ${r.jtfName}${r.areaLabel ? `, ${r.areaLabel}` : ""} (${new Date(r.date).toLocaleDateString()})`
    );
  } else {
    lines.push("Most recent: none on file.");
  }
  lines.push("");
  lines.push("2. DEPLOYMENT");
  lines.push(`Total deployed to polling: ${data.totalDeployed.toLocaleString()}`);
  lines.push(`Total QRF: ${data.totalQrf.toLocaleString()}`);
  for (const j of data.jtfDeployments) {
    lines.push(`  - ${j.jtfName}: ${j.deployedToPolling.toLocaleString()} deployed, ${j.qrf.toLocaleString()} QRF`);
  }
  lines.push("");
  lines.push("3. ELECTION OPERATIONS STATUS");
  lines.push(`Registered voters (BARMM): ${data.totalRegisteredVoters.toLocaleString()}`);
  for (const stage of data.electionOpsFunnel) {
    lines.push(`  - ${stage.label}: ${stage.count.toLocaleString()}`);
  }
  lines.push("");
  lines.push("4. ASSESSMENT");
  lines.push("[Add assessment here]");

  return lines.join("\n");
}

export async function getSituationReport(
  user: SessionUser,
  date: string = todayIso()
): Promise<SituationReport> {
  const existing = await prisma.situationReport.findUnique({
    where: { date },
    include: { updatedBy: { select: { name: true } } },
  });
  if (existing) {
    return {
      date: existing.date,
      content: existing.content,
      isAutoGenerated: existing.isAutoGenerated,
      updatedAt: existing.updatedAt.toISOString(),
      updatedByName: existing.updatedBy?.name ?? null,
    };
  }

  const content = await generateSitrepDraft(user, date);
  return {
    date,
    content,
    isAutoGenerated: true,
    updatedAt: new Date().toISOString(),
    updatedByName: null,
  };
}
