import { prisma } from "@/lib/prisma";
import { scopeJtfFilter, type SessionUser } from "@/lib/rbac";
import { getOverviewData } from "@/lib/queries/overview";
import { computeDailyAssessment } from "@/lib/queries/daily-assessment";
import { listRecentJtfAssessmentsForDailyAnalysis } from "@/lib/queries/jtf-assessments";
import { listIntelUpdates } from "@/lib/queries/intel-updates";
import { computeIntelAssessment } from "@/lib/intel-assessment";
import { getSocialMonitorData } from "@/lib/queries/social-monitor";
import { computeSocialMonitorAssessment } from "@/lib/social-monitor-assessment";
import { TOPIC_LABELS } from "@/lib/social-classifier";
import type { SocialPostTopic } from "@/generated/prisma/client";
import { reportWindow, manilaTimeLabel, todayManilaIso } from "@/lib/reporting-period";
import { getSocialListeningReport } from "@/lib/queries/social-listening";
import { listElectionProvinces, getElectionBoardData } from "@/lib/queries/election-board";

export interface SituationReport {
  date: string;
  content: string;
  isAutoGenerated: boolean;
  updatedAt: string;
  updatedByName: string | null;
}

function manilaDateLabel(date: string): string {
  return new Date(`${date}T00:00:00.000Z`).toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/** Plain-text draft assembled from on-file stats — a starting point the
 * viewer (ADMIN or WFC Intelligence/M2) always edits by hand before it
 * means anything as an actual report; never presented as a finished
 * report on its own. */
function topByFrequency(values: (string | null)[], limit: number): { label: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const v of values) {
    const label = v?.trim() || "Unspecified";
    counts.set(label, (counts.get(label) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([label, count]) => ({ label, count }));
}

export async function generateSitrepDraft(user: SessionUser, date: string): Promise<string> {
  const data = await getOverviewData(user);
  const { start, end } = reportWindow(date);
  const scopeJtfId = scopeJtfFilter(user, undefined, { allowRollup: true });

  const [
    windowIncidents,
    windowSocialPosts,
    windowIntelRows,
    jtfAssessments,
    allIntelRows,
    socialMonitorData,
    socialListeningReport,
    electionProvinces,
  ] = await Promise.all([
    prisma.incident.findMany({
      where: { jtfId: scopeJtfId, date: { gte: start, lt: end } },
      orderBy: { date: "desc" },
      include: { jtf: { select: { id: true, name: true } } },
    }),
    // Social Media Monitor and Intelligence Update are both command-wide
    // (no jtfId of their own) — every ADMIN session (the only role that
    // reaches this generator, see canAccessSituationReport) sees the full
    // picture here regardless of scopeJtfId above.
    prisma.socialMediaPost.findMany({
      where: { postedAt: { gte: start, lt: end } },
      orderBy: { postedAt: "desc" },
    }),
    prisma.intelUpdate.findMany({
      where: { date: { gte: start, lt: end } },
    }),
    // The Overall Assessment section below reuses each dashboard page's own
    // assessment engine rather than re-deriving similar analysis inline —
    // one source of truth per topic, same wording a reader would see on
    // that page itself. These three read all on-file data (not just this
    // reporting window), which is intentional: trend lines and severity
    // calls need more history than one 24h window to mean anything.
    listRecentJtfAssessmentsForDailyAnalysis(),
    listIntelUpdates(user),
    getSocialMonitorData(),
    // Most recent Social Listening report on file — not scoped to this
    // reporting window, since these are logged periodically rather than
    // once per 2200H-2200H cycle (same "latest on file" default the
    // Social Media Monitor page itself uses).
    getSocialListeningReport(),
    listElectionProvinces(user),
  ]);

  const dailyAssessment = computeDailyAssessment(data, jtfAssessments);
  const intelAssessment = computeIntelAssessment(allIntelRows);
  const socialAssessment = computeSocialMonitorAssessment(socialMonitorData);

  // Election Board (COMELEC vote-count) data is real but almost always
  // all-zero before polls close on 14 September — a per-province note is
  // only worth printing once actual encoding has started somewhere.
  const electionBoards = await Promise.all(
    electionProvinces.map((province) => getElectionBoardData(user, province))
  );
  const reportingProvinces = electionBoards.filter((b) => b.reportingPct > 0);

  const socialViolent = windowSocialPosts.filter((p) => p.classification === "VIOLENT").length;
  const socialNonViolent = windowSocialPosts.filter((p) => p.classification === "NON_VIOLENT").length;
  const socialUnclassified = windowSocialPosts.length - socialViolent - socialNonViolent;
  const socialHighlighted = windowSocialPosts.filter((p) => p.isHighlighted).length;
  const topSocialTopics = topByFrequency(
    windowSocialPosts.map((p) => (p.topic ? (TOPIC_LABELS[p.topic as SocialPostTopic] ?? p.topic) : null)),
    3
  );

  // windowIncidents is already sorted desc by date, so the first hit per
  // JTF encountered while walking it is that JTF's most recent — one pass,
  // covering every JTF on the roster (not just ones with an incident this
  // period, so a quiet JTF still shows up as "none logged").
  const mostRecentIncidentByJtf = new Map<string, (typeof windowIncidents)[number]>();
  for (const incident of windowIncidents) {
    if (!mostRecentIncidentByJtf.has(incident.jtf.id)) {
      mostRecentIncidentByJtf.set(incident.jtf.id, incident);
    }
  }

  const intelViolent = windowIntelRows.filter((r) => r.category === "VIOLENT").length;
  const intelNonViolent = windowIntelRows.filter((r) => r.category === "NON_VIOLENT").length;
  const topThreatGroups = topByFrequency(
    windowIntelRows.map((r) => r.threatGroup),
    3
  );
  const topIntelProvinces = topByFrequency(
    windowIntelRows.map((r) => r.province),
    3
  );

  const sortedIssues = socialListeningReport
    ? [...socialListeningReport.issues].sort((a, b) => b.mentions - a.mentions)
    : [];
  const sortedActivities = socialListeningReport
    ? [...socialListeningReport.significantActivities].sort((a, b) => a.rank - b.rank)
    : [];
  const topPlatform = socialListeningReport
    ? [...socialListeningReport.platformMentions].sort((a, b) => b.mentions - a.mentions)[0]
    : undefined;

  const totalAreas = data.electionOpsFunnel.find((s) => s.label === "Total Areas")?.count ?? 0;
  const paraphDelivered =
    data.electionOpsFunnel.find((s) => s.label === "Paraphernalia Delivered")?.count ?? 0;
  const acmSealed = data.electionOpsFunnel.find((s) => s.label === "ACM Tested & Sealed")?.count ?? 0;

  const lines: string[] = [];

  lines.push(`DAILY SUMMARY OF REPORTS — ${date}`);
  lines.push(`Reporting Period: ${manilaTimeLabel(start)} to ${manilaTimeLabel(end)} (2200H to 2200H)`);
  lines.push(`Date of Reporting: ${manilaDateLabel(date)}`);
  lines.push("");

  lines.push("1. EXECUTIVE SUMMARY");
  lines.push(`Command-wide severity call: ${dailyAssessment.severityLevel}. 14-day incident trend: ${dailyAssessment.incidentTrend}.`);
  lines.push(
    windowIncidents.length > 0
      ? `${windowIncidents.length} incident(s) logged this cycle across ${mostRecentIncidentByJtf.size} JTF(s).`
      : "No incidents logged this cycle."
  );
  if (socialListeningReport) {
    lines.push(
      `Social listening rates the information environment ${socialListeningReport.overallRiskLevel} risk` +
        (sortedActivities.length > 0
          ? `, with ${sortedActivities.length} significant activit${sortedActivities.length === 1 ? "y" : "ies"} under review this cycle.`
          : " for this cycle.")
    );
  } else if (windowSocialPosts.length > 0) {
    lines.push(
      `${socialViolent} of ${windowSocialPosts.length} social media post(s) this cycle carry a violent classification; ${socialHighlighted} flagged for review.`
    );
  } else {
    lines.push("No social media activity logged this cycle.");
  }
  lines.push(
    topThreatGroups.length > 0
      ? `${topThreatGroups[0].label} remains the most-cited threat picture this cycle (${topThreatGroups[0].count} report(s))${topIntelProvinces.length > 0 ? `, concentrated in ${topIntelProvinces[0].label}` : ""}.`
      : "No intelligence reports logged this cycle."
  );
  lines.push(
    `${data.totalDeployed.toLocaleString()} personnel remain deployed to polling (${data.totalQrf.toLocaleString()} QRF) BARMM-wide.`
  );
  if (totalAreas > 0) {
    lines.push(
      `Of ${totalAreas.toLocaleString()} BPE-tracked polling area(s) on file, ${paraphDelivered.toLocaleString()} have paraphernalia delivered and ${acmSealed.toLocaleString()} have ACM tested and sealed.`
    );
  }
  lines.push("");

  lines.push("2. INCIDENTS (this reporting period)");
  lines.push(`Logged: ${windowIncidents.length}`);
  lines.push(`Priority/flagged areas (overall): ${data.priorityAreaCount}`);
  lines.push("Most Recent Incident by JTF:");
  for (const j of data.jtfDeployments) {
    const r = mostRecentIncidentByJtf.get(j.jtfId);
    lines.push(
      r
        ? `  - ${j.jtfName}: ${r.type}${r.locationLabel ? `, ${r.locationLabel}` : ""} (${manilaTimeLabel(r.date)})`
        : `  - ${j.jtfName}: none logged this reporting period.`
    );
  }
  lines.push("");

  lines.push("3. SOCIAL MEDIA MONITOR (this reporting period)");
  lines.push(
    `Posts logged: ${windowSocialPosts.length} (${socialViolent} violent, ${socialNonViolent} non-violent, ${socialUnclassified} unclassified)`
  );
  lines.push(`Flagged for review: ${socialHighlighted}`);
  lines.push(
    topSocialTopics.length > 0
      ? `Most-cited topic(s): ${topSocialTopics.map((t) => `${t.label} (${t.count})`).join(", ")}`
      : "Most-cited topic(s): none logged this reporting period."
  );
  lines.push("");

  lines.push("4. SOCIAL LISTENING REPORT");
  if (socialListeningReport) {
    const coreMentions = socialListeningReport.issues.reduce((sum, i) => sum + i.mentions, 0);
    lines.push(`Period: ${socialListeningReport.periodLabel}`);
    lines.push(
      `Core mentions: ${coreMentions.toLocaleString()} | Unique sources: ${socialListeningReport.uniqueSources.toLocaleString()} | Engagement: ${socialListeningReport.engagementLabel}`
    );
    lines.push(`Overall risk level: ${socialListeningReport.overallRiskLevel} — ${socialListeningReport.riskRationale}`);
    if (sortedIssues.length > 0) {
      lines.push("Top issues by volume:");
      for (const issue of sortedIssues.slice(0, 3)) {
        lines.push(
          `  - ${issue.label}: ${issue.mentions.toLocaleString()} mentions, risk ${issue.riskLevel} (${issue.status}).`
        );
      }
    }
    if (topPlatform) {
      lines.push(`Leading platform: ${topPlatform.platform} (${topPlatform.mentions.toLocaleString()} mentions).`);
    }
    if (socialListeningReport.dominantNarratives[0]) {
      lines.push(`Dominant narrative: ${socialListeningReport.dominantNarratives[0]}`);
    }
    if (socialListeningReport.emergingNarratives[0]) {
      lines.push(`Emerging/sensitive narrative to watch: ${socialListeningReport.emergingNarratives[0]}`);
    }
    if (sortedActivities.length > 0) {
      lines.push("Significant activities (case file):");
      sortedActivities.forEach((activity, i) => {
        lines.push(`  ${i + 1}. ${activity.title}${activity.sourceUrl ? ` — Source: ${activity.sourceUrl}` : ""}`);
        lines.push(`     Assessment: ${activity.assessment}`);
      });
    } else {
      lines.push("No significant activities logged for this report.");
    }
  } else {
    lines.push("No Social Listening report logged for this cycle.");
  }
  lines.push("");

  lines.push("5. INTELLIGENCE UPDATE (this reporting period)");
  lines.push(`Reports logged: ${windowIntelRows.length} (${intelViolent} violent, ${intelNonViolent} non-violent)`);
  lines.push(
    topThreatGroups.length > 0
      ? `Most-cited threat group(s): ${topThreatGroups.map((g) => `${g.label} (${g.count})`).join(", ")}`
      : "Most-cited threat group(s): none logged this reporting period."
  );
  lines.push(
    topIntelProvinces.length > 0
      ? `Most-reported province(s): ${topIntelProvinces.map((p) => `${p.label} (${p.count})`).join(", ")}`
      : "Most-reported province(s): none logged this reporting period."
  );
  lines.push("");

  lines.push("6. DEPLOYMENT");
  lines.push(`Total deployed to polling: ${data.totalDeployed.toLocaleString()}`);
  lines.push(`Total QRF: ${data.totalQrf.toLocaleString()}`);
  for (const j of data.jtfDeployments) {
    lines.push(`  - ${j.jtfName}: ${j.deployedToPolling.toLocaleString()} deployed, ${j.qrf.toLocaleString()} QRF`);
  }
  lines.push("");

  lines.push("7. ELECTION OPERATIONS STATUS");
  lines.push(`Registered voters (BARMM): ${data.totalRegisteredVoters.toLocaleString()}`);
  for (const stage of data.electionOpsFunnel) {
    lines.push(`  - ${stage.label}: ${stage.count.toLocaleString()}`);
  }
  if (reportingProvinces.length > 0) {
    lines.push("Election Board (encoding underway):");
    for (const board of reportingProvinces) {
      const leader = board.leaderboard[0];
      lines.push(
        `  - ${board.province}: ${board.reportingPct.toFixed(1)}% reporting` +
          (leader ? `; ${leader.nameOnBallot} leads with ${leader.votesEncoded.toLocaleString()} vote(s).` : ".")
      );
    }
  }
  lines.push("");

  lines.push("8. OVERALL ASSESSMENT & TREND");
  const totalReports = windowIncidents.length + windowSocialPosts.length + windowIntelRows.length;
  lines.push(
    `${totalReports.toLocaleString()} total report(s) this reporting period — ${windowIncidents.length.toLocaleString()} incident(s), ${windowSocialPosts.length.toLocaleString()} social media post(s), ${windowIntelRows.length.toLocaleString()} intelligence report(s).`
  );
  lines.push(`Command-wide severity call (Overview/Daily Analysis): ${dailyAssessment.severityLevel}`);
  if (socialListeningReport) {
    lines.push(`Social listening risk level: ${socialListeningReport.overallRiskLevel} — ${socialListeningReport.riskRationale}`);
  }
  lines.push("");
  lines.push("From Overview / Daily Analysis:");
  for (const line of dailyAssessment.analysis) lines.push(`  - ${line}`);
  lines.push("");
  lines.push("From Intelligence Update:");
  for (const line of intelAssessment.analysis) lines.push(`  - ${line}`);
  lines.push("");
  lines.push("From Social Media Monitor:");
  for (const line of socialAssessment.analysis) lines.push(`  - ${line}`);
  lines.push("");

  lines.push("9. RECOMMENDATIONS");
  lines.push("Strategic:");
  for (const r of dailyAssessment.recommendations.strategic) lines.push(`  - ${r}`);
  lines.push("Operational:");
  for (const r of dailyAssessment.recommendations.operational) lines.push(`  - ${r}`);
  lines.push("Tactical:");
  for (const r of dailyAssessment.recommendations.tactical) lines.push(`  - ${r}`);
  if (sortedActivities[0]) {
    lines.push(
      `  - Verify and issue an attributable correction, where warranted, for the top-ranked Social Listening activity ("${sortedActivities[0].title}") before it gathers further reach.`
    );
  }
  if (topThreatGroups.length > 0) {
    lines.push(
      `  - Continue coordinated monitoring of ${topThreatGroups[0].label} activity${topIntelProvinces.length > 0 ? ` in ${topIntelProvinces[0].label}` : ""}, the most-cited threat picture this reporting cycle.`
    );
  }
  lines.push("");

  lines.push("10. COMMANDER'S ADDENDUM");
  lines.push("[Add narrative assessment here]");

  return lines.join("\n");
}

export async function getSituationReport(
  user: SessionUser,
  date: string = todayManilaIso()
): Promise<SituationReport> {
  const existing = await prisma.situationReport.findUnique({
    where: { date },
    include: { updatedBy: { select: { name: true } } },
  });
  if (existing) {
    return {
      date: existing.date,
      content: existing.content,
      isAutoGenerated: existing.isAutoGenerated,
      updatedAt: existing.updatedAt.toISOString(),
      updatedByName: existing.updatedBy?.name ?? null,
    };
  }

  const content = await generateSitrepDraft(user, date);
  return {
    date,
    content,
    isAutoGenerated: true,
    updatedAt: new Date().toISOString(),
    updatedByName: null,
  };
}
