import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireSessionUser } from "@/lib/session";
import { assertCanAccessSituationReport } from "@/lib/rbac";
import { handleApiError } from "@/lib/api-error";
import { withAudit } from "@/lib/audit";
import { getSituationReport } from "@/lib/queries/situation-report";

const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

const saveSchema = z.object({
  date: dateSchema,
  content: z.string().min(1).max(20000),
});

export async function GET(request: NextRequest) {
  try {
    const user = await requireSessionUser();
    assertCanAccessSituationReport(user);
    const date = request.nextUrl.searchParams.get("date") ?? undefined;
    const report = await getSituationReport(user, date);
    return NextResponse.json(report);
  } catch (error) {
    return handleApiError(error);
  }
}

export async function POST(request: NextRequest) {
  try {
    const user = await requireSessionUser();
    assertCanAccessSituationReport(user);
    const body = saveSchema.parse(await request.json());

    const saved = await withAudit(
      (tx) =>
        tx.situationReport.upsert({
          where: { date: body.date },
          create: {
            date: body.date,
            content: body.content,
            isAutoGenerated: false,
            updatedById: user.id,
          },
          update: {
            content: body.content,
            isAutoGenerated: false,
            updatedById: user.id,
          },
        }),
      {
        userId: user.id,
        action: "UPDATE",
        entity: "SituationReport",
        entityId: (r) => r.id,
        diff: body,
      }
    );

    return NextResponse.json(saved);
  } catch (error) {
    return handleApiError(error);
  }
}
