-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'BATTALION_STAFF';

-- CreateTable
CREATE TABLE "SituationReport" (
    "id" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SituationReport_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SituationReport_date_key" ON "SituationReport"("date");

-- AddForeignKey
ALTER TABLE "SituationReport" ADD CONSTRAINT "SituationReport_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
