"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Printer, RefreshCw, Save } from "lucide-react";
import type { SituationReport } from "@/lib/queries/situation-report";
import { SituationReportPrintView } from "@/components/situation-report-print-view";
import { formatTimestamp24h } from "@/lib/datetime";

/** "2026-09-11" -> "11 September 2026". */
function formatTitleDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  const month = d.toLocaleDateString("en-US", { month: "long", timeZone: "UTC" });
  return `${d.getUTCDate()} ${month} ${d.getUTCFullYear()}`;
}

export function SituationReportEditor({
  initial,
  canWrite,
}: {
  initial: SituationReport;
  canWrite: boolean;
}) {
  const [date, setDate] = useState(initial.date);
  const [content, setContent] = useState(initial.content);
  const [isAutoGenerated, setIsAutoGenerated] = useState(initial.isAutoGenerated);
  const [updatedAt, setUpdatedAt] = useState(initial.updatedAt);
  const [updatedByName, setUpdatedByName] = useState(initial.updatedByName);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  async function loadForDate(newDate: string) {
    setLoading(true);
    try {
      const res = await fetch(`/api/situation-report?date=${newDate}`);
      if (!res.ok) throw new Error("Failed to load report");
      const data: SituationReport = await res.json();
      setDate(data.date);
      setContent(data.content);
      setIsAutoGenerated(data.isAutoGenerated);
      setUpdatedAt(data.updatedAt);
      setUpdatedByName(data.updatedByName);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  async function handleRegenerate() {
    if (
      !isAutoGenerated &&
      !confirm("This replaces your current draft with a freshly generated one. Continue?")
    ) {
      return;
    }
    setLoading(true);
    try {
      const res = await fetch("/api/situation-report/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date }),
      });
      if (!res.ok) throw new Error("Failed to generate draft");
      const data: { content: string } = await res.json();
      setContent(data.content);
      setIsAutoGenerated(true);
      toast.success("Draft regenerated — remember to save");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  async function handleSave() {
    setSaving(true);
    try {
      const res = await fetch("/api/situation-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date, content }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error ?? "Failed to save");
      }
      const saved = await res.json();
      setIsAutoGenerated(false);
      setUpdatedAt(saved.updatedAt);
      setUpdatedByName(null);
      toast.success("Daily Summary of Reports saved");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Something went wrong");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="no-print flex flex-wrap items-end gap-3">
        <div className="flex flex-col gap-2">
          <Label htmlFor="sitrep-date">Date</Label>
          <Input
            id="sitrep-date"
            type="date"
            value={date}
            onChange={(e) => loadForDate(e.target.value)}
            className="w-40"
          />
        </div>
        {canWrite && (
          <Button variant="outline" onClick={handleRegenerate} disabled={loading || saving}>
            <RefreshCw className="size-4" />
            Regenerate Draft
          </Button>
        )}
        {canWrite && (
          <Button onClick={handleSave} disabled={loading || saving}>
            <Save className="size-4" />
            {saving ? "Saving..." : "Save"}
          </Button>
        )}
        <Button variant="outline" onClick={() => window.print()}>
          <Printer className="size-4" />
          Print
        </Button>
        <span className="text-xs text-muted-foreground">
          {!canWrite
            ? "View only"
            : isAutoGenerated
              ? "Auto-generated draft — not yet saved"
              : `Last saved ${formatTimestamp24h(updatedAt)}${updatedByName ? ` by ${updatedByName}` : ""}`}
        </span>
      </div>

      <textarea
        className="no-print min-h-[500px] w-full rounded-md border bg-background p-4 font-mono text-sm leading-relaxed focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-70"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        disabled={loading}
        readOnly={!canWrite}
      />

      {/* Print-only rendering — a <textarea>'s value doesn't reliably print
          across browsers, so the same content is mirrored into a plain
          block that's the only thing visible under @media print. The
          title here is a fixed "DAILY SUMMARY OF REPORTS as of <date>"
          format (not generateSitrepDraft's own title line, which
          SituationReportPrintView drops from the body); Reporting Period
          is always the second line generateSitrepDraft produces. */}
      <div className="print-header hidden items-center gap-3 border-b border-black pb-3 mb-3">
        {/* eslint-disable-next-line @next/next/no-img-element -- print-only
            header mark; not worth next/image's optimization pipeline for a
            one-time print render. */}
        <img src="/wesmincom-seal.png" alt="WESMINCOM seal" className="size-14" />
        <div className="text-sm">
          <div className="text-base font-bold uppercase">
            Daily Summary of Reports as of {formatTitleDate(date)}
          </div>
          <div>{content.split("\n")[1]}</div>
        </div>
      </div>
      <div className="print-only hidden">
        <SituationReportPrintView content={content} />
      </div>
    </div>
  );
}
